# https://github.com/cosmtrek/air
# Basic Air config for Go project with internal/ structure

root = "."

tmp_dir = "tmp"

[build]
  cmd = "go build -o ./bin/streamify ./cmd/main.go"
  bin = "./bin/streamify"
  full_bin = ""
  include_ext = [".go", ".tpl", ".tmpl", ".html"]
  exclude_dir = ["vendor", "tmp", "docs"]
  exclude_file = []
  exclude_regex = []
  follow_symlink = false
  delay = 1000 # ms

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[log]
  time = true

[run]
  cmd = ""
  args = []
  env = ["ENV=dev"]
  env_file = ".env"
  user = ""
  group = ""
  watch_dir = [
    "internal/",
    "cmd/",
    "go.mod",
    "go.sum"
  ]
  watch_ext = [".go"]
  ignore_dir = ["vendor", "tmp", "docs"]
  ignore_file = []
  ignore_regex = []
  stop_on_error = true
